### ISSUE TITLE
Trouble deserializing GlobalSymbol that is a member of a struct

### ISSUE THREAD

**Issue by sgpthomas** [mwillsey/symbol_table#1]
The following program crashes for me.
```rust
fn test_serde() {
    #[derive(
        serde::Serialize, serde::Deserialize, PartialEq, Eq, Debug, Clone,
    )]
    struct Test {
        field: GlobalSymbol,
    }

    let test = Test {
        field: GlobalSymbol::from("foo"),
    };

    let serialized = serde_json::to_string(&test).expect("Failed to serialize");
    println!("{serialized}");
    let _deserialized: GlobalSymbol =
        serde_json::from_str(&serialized).expect("Failed to deserialize");

    assert_eq!(
        test,
        Test {
            field: GlobalSymbol::from("foo")
        }
    );
}
```

This is the error message:
```
thread 'test_serde' panicked at 'Failed to deserialize: Error("invalid type: map, expected a borrowed string", line: 1, column: 0)', tests/test.rs:77:43
```

Am I calling this incorrectly? Is this is a bug with the serialization code?

If it's relevant. I'm actually trying to serialize an egg Egraph. I just traced the error to this library and isolated the issue.

**Comment by sgpthomas** [comment]
jk I had a typo in my deserialization.

**Comment by sgpthomas** [comment]
Found a better example of this breaking:
```
#[cfg(feature = "global")]
#[cfg(feature = "serde")]
#[test]
fn test_serde() {
    let test: GlobalSymbol = GlobalSymbol::from("foo");

    let file = std::fs::OpenOptions::new()
        .read(true)
        .write(true)
        .create(true)
        .truncate(true)
        .open("test.chkpt")
        .expect("Failed to open file");

    serde_json::to_writer(file, &test).expect("Failed to serialize");

    let file = std::fs::OpenOptions::new()
        .read(true)
        .open("test.chkpt")
        .expect("Failed to open file");
    // log::info!("{serialized:?}");
    let deserialized =
        serde_json::from_reader(file).expect("Failed to deserialize");

    assert_eq!(test, deserialized);
}
```

Changing the serde bound on `GlobalSymbol` to `#[serde(from = "String", ...]` fixes the issue. A weird thing is that this only happens when you serialize to a file. It doesn't happen serialize / deserialize form strings. I also tried with `ciborium` as the serialization/deserialization backend and I get the same behavior.

**Comment by mwillsey** [comment]
The bug happens when you _serialize_ to a file? Or only when you deserialize?

**Comment by sgpthomas** [comment]
Only when you deserialize from a file. Sorry, I was unclear

**Comment by mwillsey** [comment]
If you're editing the code could you try a manual Deserialize impl? Should look something like this: https://docs.rs/serde/latest/src/serde/de/impls.rs.html#623-630, followed by actually creating the symbol.

**Comment by sgpthomas** [comment]
So I've done a bit more investigation; following your advice of manually implementing the trait. Here's my best guess for what's going on.

When you are de-serializing a Rust string, `serde_json` calls `visit_borrowed_str`. This function has a parameter with a lifetime that is the same as the visitor which means that the following definition works:

```rust
struct MyVisitor;

impl<'de> serde::de::Visitor<'de> for MyVisitor {
    type Value = &'de str;

    fn expecting(
        &self,
        formatter: &mut std::fmt::Formatter,
    ) -> std::fmt::Result {
        formatter.write_str("a fish")
    }

    fn visit_borrowed_str<E>(self, v: &'de str) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        Ok(v)
    }
}

impl<'de> serde::Deserialize<'de> for GlobalSymbol {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let x = deserializer.deserialize_str(MyVisitor)?;
        Ok(x.into())
    }
}
```

Crucially, `Value` can be `&'de str` and the `visit_borrowed_str` can return a thing of this type. I believe this is more or less equivalent to what the `#[serde(from = &str)]` gives you, though it's very hard to read the macro expanded code.

However, when you are reading from a file, instead of a string, `visit_str` is called *instead* of `visit_borrowed_str`. This function has the signature:
```rust
fn visit_str<E>(self, v: &str) -> Result<Self::Value, E>
    where
        E: serde::de::Error
```

Here, the `v` parameter has an ephermal lifetime, rather than the same one as the Visitor. Now you can't have `Value` be `&str`. You need it to be something owned instead. Either `String` or `GlobalSymbol` works. Here's a complete implementation that works:
```rust
struct MyVisitor;

impl<'de> serde::de::Visitor<'de> for MyVisitor {
    type Value = GlobalSymbol;

    fn expecting(
        &self,
        formatter: &mut std::fmt::Formatter,
    ) -> std::fmt::Result {
        formatter.write_str("a fish")
    }

    fn visit_str<E>(self, v: &str) -> Result<Self::Value, E>
    where
        E: serde::de::Error,
    {
        Ok(v.into())
    }
}

impl<'de> serde::Deserialize<'de> for GlobalSymbol {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let x = deserializer.deserialize_str(MyVisitor)?;
        Ok(x)
    }
}
```

I guess using `#[serde(from = String)]` works because it explicitly copies the String before interning it, making the lifetimes work out. But I'm a little fuzzy on this. A manual implementation of Deserialize seems more ideal to me, because you don't need to copy the string.

This all seems to be an interaction with the deserialization backend and the Deserialization model. I have no idea if this is a problem with more backends than `serde_json` and `ciborium`. But afaict the deserialization backend gets to choose what visitor methods to call, so it seems good to have all of them functioning.

**Comment by sgpthomas** [comment]
Could you make a new release that includes this change?

**Comment by mwillsey** [comment]
Done, v0.3.0 is out: https://crates.io/crates/symbol_table
