### ISSUE TITLE
Using `symbol_table` in a single-threaded context

### ISSUE THREAD

**Issue by rachitnigam** [mwillsey/symbol_table#3]
Is there a way to not pay the cost of locking/sharding when I'm guaranteed to be using in a single-threaded context only? If not, would it reasonable to expose a `const`-param mechanism to the `SymbolTable` structure that disables the locking and sharding?

**Comment by mwillsey** [comment]
I was operating on the assumption that locking is very low cost if not contended, probably a single atomic operation.

**Comment by rachitnigam** [comment]
I was noticing substantial overhead compared to the `string_interner` library when I reimplemented `GlobalSymbol` using it without any of the sharding/locking. I also assume that locking might disable certain code-motion/inlining optimizations that can otherwise be performed

Anyways, okay with closing if `symbol_table` is not really meant to support the single-threaded use case but might be worth micro-benchmarking a bit if single-thread support matters too

**Comment by mwillsey** [comment]
I'm not super concerned with maximum single-threaded performance at the moment, so I'll close this for now.
