### ISSUE TITLE
Interning `&'static str` at compile time

### ISSUE THREAD

**Issue by rachitnigam** [mwillsey/symbol_table#4]
Is there any way to intern strings at compile time? I have a bunch of static strings floating around in my program that I'd like to intern in the global symbol table and only use symbol structs at runtime. I'm assuming probably not because we'd need some way to mark a bunch of functions as `const` in order to add strings at compile time.

**Comment by mwillsey** [comment]
There is not. The [`string_cache`](https://docs.rs/string_cache/latest/string_cache/) crate supports it, but it's a little too complicated for this little crate.
